#!/usr/bin/env bash
set -euo pipefail

repo=${LAW_LINT_ROOT:-$(git rev-parse --show-toplevel)}
output=${LAWS_LOCK_OUTPUT:-$repo/docs/laws.lock}
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
{
  echo '# @generated by `make laws-lock` — Build Law numbering pin. Numbers are PERMANENT:'
  echo '# new laws APPEND, none is inserted, re-ordered or re-used. Regenerate only on an APPEND.'
  perl -ne 'if (/^([0-9]+)\. \*\*([^*]+)\*\*/) { print "$1\t$2\n" }' "$repo/CLAUDE.md"
} >"$tmp"
count=$(awk -F '\t' '/^[0-9]+\t/{n++} END{print n+0}' "$tmp")
((count > 0)) || { echo 'gen-laws-lock: no laws found' >&2; exit 1; }
cp "$tmp" "$output"
