#!/usr/bin/env bash
set -euo pipefail

repo=${SPEC_LINT_ROOT:-$(git rev-parse --show-toplevel)}
output=${INVARIANTS_LOCK_OUTPUT:-$repo/docs/invariants.lock}
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

{
  echo '# @generated by `make invariants-lock` — SPEC invariant ID pin. IDs are PERMANENT:'
  echo '# new invariants APPEND; none is inserted, re-ordered, re-used or silently retitled.'
  echo '# Regenerate ONLY on a deliberate append/retitle — the DIFF of this file is the review.'
  while IFS= read -r -d '' spec; do
    rel=${spec#"$repo"/}
    perl -0777 -e '
      my $path = shift @ARGV;
      local $/;
      my $text = <>;
      while ($text =~ /^\s*\d+\.\s+\*\*((?:[A-Z]+-)?INV-\d+)\s+—\s+(.*?)\*\*/msg) {
        my ($id, $title) = ($1, $2);
        $title =~ s/\s+/ /g;
        $title =~ s/^\s+|\s+$//g;
        print "$path\t$id\t$title\n";
      }
    ' "$rel" "$spec"
  done < <(find "$repo/kernel" -name SPEC.md -type f -print0 | sort -z)
} > "$tmp"

duplicates=$(awk -F '\t' 'NF == 3 { key=$1 FS $2; count[key]++ } END { for (key in count) if (count[key] > 1) print key }' "$tmp")
if [ -n "$duplicates" ]; then
  echo "duplicate invariant id:" >&2
  echo "$duplicates" >&2
  exit 1
fi
if [ "$(awk -F '\t' 'NF == 3 { count++ } END { print count+0 }' "$tmp")" -eq 0 ]; then
  echo 'no invariant declarations found' >&2
  exit 1
fi
cp "$tmp" "$output"
