#!/usr/bin/env bash
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
{
 echo '<!-- @generated by scripts/gen-index.sh — regenerate with `make index`; never hand-edit (Law 1) -->'; echo '# Decision Index'; echo
 n=0
 while IFS= read -r f; do
  title=$(sed -n 's/^# //p' "$f" | head -n1); title=${title#*: }; status=$(sed -n 's/^\*\*Status:\*\* //p' "$f" | head -n1); date=$(sed -n 's/^\*\*Date:\*\* //p' "$f" | head -n1)
  [ -n "$title" ] || exit 1
  printf '%s\n' "- [$(basename "$f" .md): $title]($(basename "$f")) — ${status:-Unknown} (${date:-undated})"
  n=$((n+1))
 done < <(find docs/decisions -maxdepth 1 -type f -name 'VD-*.md' | sort)
 [ "$n" -gt 0 ] || exit 1
} > "$tmp"
if [ -n "${GEN_INDEX_OUTPUT:-}" ]; then cp "$tmp" "$GEN_INDEX_OUTPUT"; else cp "$tmp" docs/decisions/INDEX.md; fi
