#!/usr/bin/env bash
set -euo pipefail

repo=$(git rev-parse --show-toplevel)
mode=${1:---check}
verdict_dir=${P6_INTEGRITY_VERDICTS:-$repo/docs/verification/verdicts}
artifact=${P6_INTEGRITY_ARTIFACT:-$repo/docs/verification/p6-artifact-integrity.md}
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
wire=0 documentary=0

fail() { echo "p6-artifact-integrity: $*" >&2; exit 1; }

while IFS= read -r file; do
  name=${file##*/}
  first=$(sed -n '1p' "$file")
  if [[ $first != '---' ]]; then
    documentary=$((documentary + 1))
    continue
  fi
  second=$(sed -n '2p' "$file")
  if [[ $second == \{* ]]; then
    declared_path=$(sed -n '2s/.*"artifact_path":"\([^"]*\)".*/\1/p' "$file")
    declared_digest=$(sed -n '2s/.*"artifact_sha256":"\([0-9a-f]\{64\}\)".*/\1/p' "$file")
    reviewed=$(sed -n '2s/.*"reviewed_commit":"\([0-9a-f]\{40,64\}\)".*/\1/p' "$file")
    actual=$(sed -E '2s/("artifact_path":"[^"]*",)"artifact_sha256":"[0-9a-f]{64}"/\1"artifact_sha256":"0000000000000000000000000000000000000000000000000000000000000000"/' "$file" | sha256sum | awk '{print $1}')
  else
    declared_path=$(awk '$1 == "artifact_path:" {print $2; exit}' "$file")
    declared_digest=$(awk '$1 == "artifact_sha:" {print $2; exit}' "$file")
    reviewed=$(awk '$1 == "reviewed_commit:" {print $2; exit}' "$file")
    actual=$(sed -E 's/^artifact_sha: [0-9a-f]{64}$/artifact_sha: 0000000000000000000000000000000000000000000000000000000000000000/' "$file" | sha256sum | awk '{print $1}')
  fi
  expected_path=docs/verification/verdicts/$name
  [[ $declared_path == "$expected_path" ]] || fail "$name path=$declared_path want=$expected_path"
  [[ $declared_digest =~ ^[0-9a-f]{64}$ ]] || fail "$name missing valid self-digest"
  [[ $actual == "$declared_digest" ]] || fail "$name digest=$actual declared=$declared_digest"
  if [[ -n $reviewed ]]; then
    git -C "$repo" cat-file -e "$reviewed^{commit}" 2>/dev/null || fail "$name reviewed commit does not resolve: $reviewed"
  fi
  wire=$((wire + 1))
done < <(find "$verdict_dir" -maxdepth 1 -type f -name '*.md' -print | LC_ALL=C sort)

((wire > 0 && documentary > 0)) || fail "inert enumeration wire=$wire documentary=$documentary"

p5_exhibit=$repo/docs/verification/verdicts/p5-plan-draft-as-reviewed.md
p5_expected=$(sed -n 's/.*sha256 `\([0-9a-f]\{64\}\)`.*/\1/p' "$repo/docs/verification/verdicts/p5-adjudication-round1.md" | head -1)
p5_actual=$(sha256sum "$p5_exhibit" | awk '{print $1}')
[[ $p5_actual == "$p5_expected" ]] || fail "P5 adjudication exhibit digest mismatch"

p6_exhibit=$repo/docs/plans/P6-CONSOLIDATION-PLAN-draft1.md
p6_expected=$(sed -n 's/^\*\*Artifact SHA-256:\*\* `\([0-9a-f]\{64\}\)`.*/\1/p' "$repo/docs/verification/verdicts/p6-consolidation-plan-round1.md")
p6_actual=$(sha256sum "$p6_exhibit" | awk '{print $1}')
[[ $p6_actual == "$p6_expected" ]] || fail "P6 adjudication exhibit digest mismatch"

{
  printf '# P6 Task 3 — artifact integrity audit\n\n'
  printf '<!-- @generated by scripts/p6-artifact-integrity.sh --write; do not hand-edit -->\n\n'
  printf 'Result: PASS. Schema-bearing verdicts: %d; documentary verdict artifacts: %d.\n\n' "$wire" "$documentary"
  printf 'For every schema-bearing verdict, the declared artifact path equals its committed path, '
  printf 'the normalized self-digest reproduces exactly, and any declared reviewed commit resolves. '
  printf 'Documentary verdicts were enumerated without being reinterpreted as wire artifacts.\n\n'
  printf '| Provenance binding | Expected | Actual | Result |\n|---|---|---|---|\n'
  printf '| P5 adjudication exhibit | `%s` | `%s` | PASS |\n' "$p5_expected" "$p5_actual"
  printf '| P6 round-1 plan exhibit | `%s` | `%s` | PASS |\n' "$p6_expected" "$p6_actual"
  printf '\nCommand: `scripts/p6-artifact-integrity.sh --check`.\n'
} >"$tmp"

case $mode in
  --write) install -m 0644 "$tmp" "$artifact" ;;
  --check)
    [[ -f $artifact ]] || fail 'audit artifact missing'
    diff -u "$artifact" "$tmp" || fail 'audit artifact stale'
    ;;
  *) echo 'usage: scripts/p6-artifact-integrity.sh [--write|--check]' >&2; exit 2 ;;
esac
