#!/usr/bin/env bash
set -euo pipefail

repo=$(git rev-parse --show-toplevel)
mode=${1:---check}
artifact=${P6_ROUTE_ARTIFACT:-$repo/docs/verification/p6-event-route-matrix.md}
rows=$repo/docs/plans/p6-census-rows.tsv
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

pairs=(
  'git:commit.recorded'
  'checks:check.run'
  'sessions:session.observed'
  'reviews:review.verdict'
  'reviews:requirement.reviewed'
  'github:github.workflow_run'
  'github:github.deployment'
  'intent.records:business_decision.recorded'
  'intent.records:requirement.recorded'
  'intent.records:change_intent.recorded'
  'intent.specdir:business_decision.recorded'
  'intent.specdir:requirement.recorded'
  'intent.specdir:change_intent.recorded'
)
consumers=(projection verify twin gates)

declare -A census=()
while IFS=$'\t' read -r id category subject _; do
  [[ $category == C5 ]] || continue
  [[ -z ${census[$subject]+x} ]] || { echo "p6-route-matrix: duplicate $subject" >&2; exit 1; }
  census[$subject]=$id
done <"$rows"
[[ ${#census[@]} -eq 52 ]] || { echo "p6-route-matrix: expected 52 C5 rows, got ${#census[@]}" >&2; exit 1; }

for pair in "${pairs[@]}"; do
  for consumer in "${consumers[@]}"; do
    subject=route:$pair:$consumer
    [[ -n ${census[$subject]+x} ]] || { echo "p6-route-matrix: missing $subject" >&2; exit 1; }
  done
done

declare -A citations=(
  [projection]='kernel/internal/projections/projection_test.go::TestSupportedEventMatrix'
  [verify]='kernel/internal/cli/cli_test.go::TestVerifyChecksEveryStageError'
  [twin]='kernel/internal/twin/replay_test.go::TestReplayProofCoversEveryRegisteredEventPair'
  [gates]='kernel/internal/gates/gates_integration_test.go::TestCurrentGateEstateEventRoutes'
)
for citation in "${citations[@]}"; do
  file=${citation%%::*}; test=${citation##*::}
  [[ -f $repo/$file ]] && rg -q "^func[[:space:]]+$test\\(" "$repo/$file" || {
    echo "p6-route-matrix: unresolved citation $citation" >&2
    exit 1
  }
done

code_commit=$(git -C "$repo" log -1 --format=%H -- kernel/internal/projections kernel/internal/cli kernel/internal/twin kernel/internal/gates)
[[ $code_commit =~ ^[0-9a-f]{40}$ ]] || { echo 'p6-route-matrix: no code commit' >&2; exit 1; }

{
  printf '# P6 Task 3 — complete event route matrix\n\n'
  printf '<!-- @generated by scripts/p6-route-matrix.sh --write; do not hand-edit -->\n\n'
  printf '**Code commit:** `%s`  \n' "$code_commit"
  printf '**Universe:** 13 registered source-kind pairs × 4 consumers = 52 classified cells.\n\n'
  printf '| C5 row | Source | Kind | Consumer | Route | Proving test |\n'
  printf '|---|---|---|---|---|---|\n'
  for pair in "${pairs[@]}"; do
    source=${pair%%:*}; kind=${pair#*:}
    for consumer in "${consumers[@]}"; do
      route=consume
      if [[ $consumer == gates && ( $source == sessions || $source == github ) ]]; then route=ignore; fi
      subject=route:$pair:$consumer
      printf '| %s | `%s` | `%s` | %s | %s | `%s` |\n' "${census[$subject]}" "$source" "$kind" "$consumer" "$route" "${citations[$consumer]}"
    done
  done
  printf '\nCounts: `consume=49 ignore=3 reject=0 unclassified=0`. Projection, verify, and twin '
  printf 'consume all registered pairs. The current gate estate intentionally ignores sessions and '
  printf 'the two GitHub observation kinds; this does not narrow the generic evaluator contract.\n\n'
  printf 'Frozen identity check: `vera.replay.v1` remains unchanged; the twin proof test binds every '
  printf 'pair and payload digest without editing any historical vector.\n'
} >"$tmp"

case $mode in
  --write) install -m 0644 "$tmp" "$artifact" ;;
  --check)
    [[ -f $artifact ]] || { echo 'p6-route-matrix: artifact missing' >&2; exit 1; }
    diff -u "$artifact" "$tmp" || { echo 'p6-route-matrix: artifact stale' >&2; exit 1; }
    ;;
  *) echo 'usage: scripts/p6-route-matrix.sh [--write|--check]' >&2; exit 2 ;;
esac
