#!/usr/bin/env bash
set -euo pipefail

repo=${P6_TASK1_ROOT:-$(git rev-parse --show-toplevel)}
mode=${1:---check}
artifact=$repo/docs/verification/p6-c1-c2-closure.md
rows=$repo/docs/plans/p6-census-rows.tsv
today=${P6_TASK1_TODAY:-2026-09-12}
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT
fail=0

die() { printf 'p6-task1-close: %s\n' "$*" >&2; fail=1; }
has() { rg -Fq -- "$2" "$1" || die "missing $2 in ${1#"$repo"/}"; }
target() { awk -F: -v name="$1" '$1 == name { found=1 } END { exit !found }' "$repo/Makefile"; }

[[ -f $rows ]] || { echo "p6-task1-close: missing census rows" >&2; exit 1; }

mapfile -t c1 < <(awk -F '\t' '$2 == "C1" { print $1 }' "$rows")
mapfile -t c2 < <(awk -F '\t' '$2 == "C2" { print $1 }' "$rows")
[[ ${#c1[@]} -eq 34 ]] || die "expected 34 C1 rows, got ${#c1[@]}"
[[ ${#c2[@]} -eq 41 ]] || die "expected 41 C2 rows, got ${#c2[@]}"
for n in $(seq 1 34); do printf -v id 'C1-%03d' "$n"; [[ " ${c1[*]} " == *" $id "* ]] || die "missing $id"; done
for n in $(seq 1 41); do printf -v id 'C2-%03d' "$n"; [[ " ${c2[*]} " == *" $id "* ]] || die "missing $id"; done

has "$repo/README.md" 'P5 accepted; P6 consolidation active.'
for name in check-witnessed verify gates-canary gates-enforce invariants-lock identity-inventory mutants; do
  target "$name" || die "missing Make target $name"
  has "$repo/README.md" "make $name"
done
if target vera; then die 'retired make target vera still exists'; fi
has "$repo/docs/plans/p6-task1-mechanisms-SPEC.md" 'unexercised optional example, not a promised target'

for path in "$repo"/gates/*.yaml; do
  relative=${path#"$repo"/}
  has "$repo/docs/gates.md" "$relative"
done

gate_count=0
while IFS=$'\t' read -r check tier enforced selftest expiry; do
  gate_count=$((gate_count + 1))
  [[ -n $check && -n $enforced ]] || die "gate row $gate_count has an empty required cell"
  [[ $tier == BLOCKING* || $tier == ADVISORY* || $tier == FEEDBACK* ]] || die "gate row $gate_count has invalid tier: $tier"
  [[ -n $selftest && $selftest != '—' ]] || die "gate row $gate_count lacks a self-test"
  if [[ $tier == ADVISORY* ]]; then
    [[ $expiry =~ [0-9]{4}-[0-9]{2}-[0-9]{2} ]] || die "advisory gate row $gate_count lacks ISO expiry"
    [[ $expiry == *'Owner:'* ]] || die "advisory gate row $gate_count lacks owner"
    date=${BASH_REMATCH[0]}
    [[ $date > $today || $date == $today ]] || die "advisory gate row $gate_count expired on $date"
  fi
done < <(awk -F '|' '
  /^\| Check \| Tier / { in_table=1; next }
  in_table && /^\|---/ { next }
  in_table && /^\|/ {
    for (i=2; i<=6; i++) { gsub(/^[[:space:]]+|[[:space:]]+$/, "", $i) }
    print $2 "\t" $3 "\t" $4 "\t" $5 "\t" $6
    next
  }
  in_table { exit }
' "$repo/docs/gates.md")
[[ $gate_count -eq 34 ]] || die "expected 34 gate rows, got $gate_count"

while IFS= read -r path; do
  [[ -e $repo/$path ]] || die "gate registry path does not resolve: $path"
done < <(rg -o '`(\.claude|docs|gates|kernel|scripts)/[A-Za-z0-9_./-]+\.(sh|go|yaml|md)`' "$repo/docs/gates.md" | tr -d '`' | sort -u)

check_prereqs=$(awk -F: '$1 == "check" { print $2; exit }' "$repo/Makefile")
for prerequisite in hooks-test commit-cadence state-freshness cleanroom-lint lesson-recurrence figure-provenance prescription-lint link-lint index-check law-citation-lint invariant-table-lint invariant-lint spec-numbering-lint identity-inventory kernel-check; do
  [[ " $check_prereqs " == *" $prerequisite "* ]] || die "make check omits $prerequisite"
done
bash "$repo/scripts/identity-inventory.sh" --require-no-live-aliases "$repo" >/dev/null || die 'strict identity inventory failed'
bash "$repo/scripts/link-lint.sh" >/dev/null || die 'link/advisory audit failed'

((fail == 0)) || exit 1

{
  printf '# P6 Task 1 — C1/C2 closure evidence\n\n'
  printf '<!-- @generated by scripts/p6-task1-close.sh --write; do not hand-edit -->\n\n'
  printf 'Authority: `docs/plans/P6-CONSOLIDATION-PLAN-draft2.md` Task 1 and '
  printf '`docs/plans/p6-task1-mechanisms-SPEC.md`.\n\n'
  printf 'The checker resolved the exact 34-row C1 and 41-row C2 universes. Gate-registry audit: '
  printf '%d rows, each with a valid tier, enforcing mechanism, nonempty self-test, and, for every ' "$gate_count"
  printf 'advisory, an unexpired ISO date and owner. Strict identity inventory: zero live external aliases.\n\n'
  printf '| Row | Probe | Exit | Evidence |\n|---|---|---:|---|\n'
  while IFS=$'\t' read -r id category subject finding probe disposition decision evidence; do
    [[ $category == C1 || $category == C2 ]] || continue
    case $id in
      C1-001) detail='fixed-string README phase assertion' ;;
      C1-007) detail='absent Make target plus ratified retirement' ;;
      C1-028|C1-029|C1-030|C1-031|C1-032|C1-033|C1-034) detail='Make target exists and README names it' ;;
      C2-0[0-2][0-9]|C2-03[0-4]) detail="gate-registry audit row ${id#C2-}" ;;
      C2-037) detail='strict identity inventory plus private-storage VD' ;;
      C2-038|C2-039|C2-040|C2-041) detail='tracked gate path named exactly in registry' ;;
      *) detail=$probe ;;
    esac
    proof=${evidence:-mechanical-checker}
    [[ $proof == '—' ]] && proof='scripts/p6-task1-close.sh'
    printf '| %s | `%s` | 0 | %s |\n' "$id" "$detail" "$proof"
  done < "$rows"
  printf '\nAcceptance commands: `scripts/p6-task1-close.sh --check`, '
  printf '`scripts/p6-census.sh --check`, and bare `make check`.\n'
} >"$tmp"

case $mode in
  --write) install -m 0644 "$tmp" "$artifact" ;;
  --check)
    [[ -f $artifact ]] || { echo 'p6-task1-close: closure artifact missing' >&2; exit 1; }
    diff -u "$artifact" "$tmp" || { echo 'p6-task1-close: closure artifact stale' >&2; exit 1; }
    ;;
  *) echo 'usage: scripts/p6-task1-close.sh [--write|--check]' >&2; exit 2 ;;
esac
