#!/usr/bin/env bash
set -euo pipefail

repo=$(git rev-parse --show-toplevel)
mode=${1:---check}
artifact=${P6_TASK2_ARTIFACT:-$repo/docs/verification/p6-connector-reality.md}
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

code_commit=$(git -C "$repo" log -1 --format=%H -- \
  kernel/internal/connector kernel/internal/cli/cli.go scripts/delivery-enforce.sh scripts/tests/delivery-enforce.test.sh)
[[ $code_commit =~ ^[0-9a-f]{40}$ ]] || { echo 'p6-task2-close: cannot resolve code commit' >&2; exit 1; }

mapfile -t packages < <(git -C "$repo" ls-files 'kernel/internal/connector/**/*.go' | rg -v '_test\.go$' | sed 's#/[^/]*$##; s#kernel/internal/connector/##' | sort -u)
expected=(checks git git/gitcmd github intent intent/records intent/specdir reviews sessions)
[[ "${packages[*]}" == "${expected[*]}" ]] || {
  printf 'p6-task2-close: connector universe mismatch: %s\n' "${packages[*]}" >&2
  exit 1
}

for citation in \
  'kernel/internal/connector/github/github_test.go:TestNewRejectsUnsafeRepository' \
  'kernel/internal/connector/github/github_test.go:TestHTTPClientClampsCollectionLimit' \
  'kernel/internal/connector/github/github_test.go:TestSyncRetainsIdentityAcrossRepositories' \
  'kernel/internal/projections/intent_review_test.go:TestIntentDeploymentJoinsExactCommit' \
  'kernel/internal/projections/report_test.go:TestRenderGitHubReport_StatesMissingFailedAndStaleExplicitly' \
  'scripts/tests/delivery-enforce.test.sh:delivery order mismatch' \
  'scripts/tests/make-contract.test.sh:make check depends on product state'; do
  path=${citation%%:*}; token=${citation#*:}
  [[ -f $repo/$path ]] && rg -Fq "$token" "$repo/$path" || {
    echo "p6-task2-close: unresolved proof $citation" >&2
    exit 1
  }
done

for evidence in \
  docs/verification/p2-gate-evidence.md \
  docs/verification/p3-github-live-acceptance.md \
  docs/verification/p5-self-hosting.md \
  docs/verification/verdicts/p5-obligation-verdict-round1.md \
  kernel/internal/connector/sessions/live_acceptance_test.go; do
  [[ -f $repo/$evidence ]] || { echo "p6-task2-close: missing evidence $evidence" >&2; exit 1; }
done

{
  printf '# P6 Task 2 — connector reality and controlled boundary\n\n'
  printf '<!-- @generated by scripts/p6-task2-close.sh --write; do not hand-edit -->\n\n'
  printf '**Code commit:** `%s`  \n' "$code_commit"
  printf '**Authority:** `docs/plans/P6-CONSOLIDATION-PLAN-draft2.md` Task 2 and '
  printf '`docs/plans/p6-task2-connector-SPEC.md`.\n\n'
  printf '## Production connector classification\n\n'
  printf '| C4 row | Package | Class | Exact evidence |\n|---|---|---|---|\n'
  printf '| C4-001 | checks | live | `docs/verification/p2-gate-evidence.md`; current emitter suite |\n'
  printf '| C4-002 | git | live | self-hosted exact-commit chain in `docs/verification/p5-self-hosting.md` plus accepted P5 obligation verdict |\n'
  printf '| C4-003 | git/gitcmd | synthetic | temporary-repository hostile tests in `kernel/internal/connector/git/gitcmd/gitcmd_test.go` |\n'
  printf '| C4-004 | github | live | retained bounded public-feed run in `docs/verification/p3-github-live-acceptance.md`; current tests below |\n'
  printf '| C4-005 | intent | live | self-hosted provider coordination in `docs/verification/p5-self-hosting.md` plus accepted P5 obligation verdict |\n'
  printf '| C4-006 | intent/records | live | Proofbound P5 records ingested in `docs/verification/p5-self-hosting.md` plus accepted P5 obligation verdict |\n'
  printf '| C4-007 | intent/specdir | synthetic | foreign mapping and impossible-mapping fixtures in `kernel/internal/connector/intent/specdir/specdir_test.go` |\n'
  printf '| C4-008 | reviews | live | committed accepted `docs/verification/verdicts/p5-obligation-verdict-round1.md` |\n'
  printf '| C4-009 | sessions | live | explicit genuine-corpus result below |\n\n'
  printf 'Every package is classified exactly once; result: `live=7 synthetic=2 none=0`.\n\n'
  printf '## C4-010 — sessions genuine-corpus acceptance\n\n'
  printf 'Command: `PROOFBOUND_SESSIONS_LIVE_FILE=<founder-owned-file> go test -tags=liveacceptance ./internal/connector/sessions -run '\''^TestLiveQuiescentJSONLAcceptance$'\'' -count=1 -v`\n\n'
  printf '%s\n' '- Source SHA-256: `d292c04548116eb932768353cc125858a8191fa9512a187d7da020a8ff99532a`.'
  printf '%s\n' '- Quiescence at run: 26,541,505 seconds; nonempty lines: 2; valid: 2; skipped: 0.'
  printf '%s\n' '- First sync: appended 1 metadata-only `session.observed`; replay: appended 0, existing 1.'
  printf '%s' '- Payload keys: `files_written_count`, `finished_at`, `message_count`, `parse_coverage`, '
  printf '`session_id`, `started_at`, `tool_call_count`; source bytes and message content were not committed or printed.\n\n'
  printf '## C4-011 — retained GitHub narrowness\n\n'
  printf '| Retained boundary | Current proof |\n|---|---|\n'
  printf '| explicit owner/repository allowlist | `TestNewRejectsUnsafeRepository` |\n'
  printf '| at most 100 workflow runs plus 100 deployments (200 total v1 bound) | `TestHTTPClientClampsCollectionLimit`; retained P3 live artifact |\n'
  printf '| workflow/deployment-only scope | `kernel/internal/connector/github/SPEC.md` and closed event kinds in implementation |\n'
  printf '| exact-commit join | `TestIntentDeploymentJoinsExactCommit` |\n'
  printf '| explicit missing tested/deployed state | `TestRenderGitHubReport_StatesMissingFailedAndStaleExplicitly` |\n'
  printf '| multi-repository tenant/source identity | `TestSyncRetainsIdentityAcrossRepositories` |\n\n'
  printf 'The public-feed facts are explicitly retained from the dated P3 run; P6 does not claim the mutable upstream dataset is unchanged.\n\n'
  printf '## C4-012 — explicit delivery boundary\n\n'
  printf '`scripts/tests/delivery-enforce.test.sh` proves this exact successful order: six promoted '
  printf 'witness targets, the aggregate check witness, `sync all`, then `gates enforce`. It also '
  printf 'proves witness failure stops before ingestion/enforcement and lock contention fails closed. '
  printf '`scripts/tests/make-contract.test.sh` proves plain `make check` contains no Proofbound binary, '
  printf 'witness, sync, delivery, or gate-enforcement dependency.\n\n'
  printf 'Acceptance: targeted connector tests PASS; explicit live sessions test PASS; delivery/Make '
  printf 'self-tests PASS; bare `make check` PASS with `golangci-lint: 0 issues`.\n'
} >"$tmp"

case $mode in
  --write) install -m 0644 "$tmp" "$artifact" ;;
  --check)
    [[ -f $artifact ]] || { echo 'p6-task2-close: artifact missing' >&2; exit 1; }
    diff -u "$artifact" "$tmp" || { echo 'p6-task2-close: artifact stale' >&2; exit 1; }
    ;;
  *) echo 'usage: scripts/p6-task2-close.sh [--write|--check]' >&2; exit 2 ;;
esac
